# Generated by Django 4.0.1 on 2022-01-20 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_contact', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('S', 'Seller'), ('C', 'Customer')], default='C', max_length=1)),
            ],
            options={
                'ordering': ['username', 'joining_date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles_type', models.CharField(choices=[('T', 'Truck'), ('C', 'Car'), ('B', 'Bike'), ('P', 'Part')], default='C', max_length=1)),
                ('manufacturer', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('model', models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2023)])),
                ('displacement', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('likes', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='store.user')),
            ],
            options={
                'ordering': ['name', 'price', 'likes', 'displacement'],
            },
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='store.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='store.user')),
            ],
        ),
    ]
