# Generated by Django 4.0.1 on 2022-01-21 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ['name', 'price', 'likes', 'distance_traveled']},
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='displacement',
            new_name='distance_traveled',
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='store.user'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='model',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
