# Generated by Django 4.0.1 on 2022-01-21 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_address_alter_user_whatsapp_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
