# Generated by Django 4.0.1 on 2022-01-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_like_remove_chat_date_remove_chat_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeditem',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedvehicle', to='store.vehicles'),
        ),
    ]
