# Generated by Django 4.0.1 on 2022-01-22 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_like_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ['model', 'price', 'likes', 'distance_traveled']},
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='name',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='model_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2023)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='model',
            field=models.CharField(max_length=255),
        ),
    ]
