# Generated by Django 4.0.1 on 2022-01-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_vehicles_options_remove_vehicles_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='likeditem',
            unique_together={('like', 'vehicle')},
        ),
    ]
