# Generated by Django 4.0.1 on 2022-01-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeditem',
            name='like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_item', to='store.like'),
        ),
        migrations.AlterField(
            model_name='likeditem',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_vehicle', to='store.vehicles'),
        ),
    ]
